### ISSUE TITLE
TEAMROCKET#27: Ingredient Search

### ISSUE THREAD

**Issue by skmartinelli** [cse112-sp22-group3/rocketrecipes#27]
**Briefly describe the problem/feature**
We want to implement a way to refine the search by adding or removing specific ingredients to the search (See allrecipes.com). We would need to add some front end and then also modify the search algorithm for this.

**Point Estimate (in Fibonacci numbers)**
3

**What area of code does this affect?**
search page html css and js

**What needs to be done (at a glance)?**
- Add front end for adding ingredients to add or remove
- Add function to parse ingredients list
- Alter search to account for ingredient restrictions

**Reviewer**
@skmartinelli @williamcsimpson @lramos0 @alvinsandiego 
**Assignee**
@alvinsandiego @skmartinelli @williamcsimpson

**Comment by helloserina** [comment]
Did y'all need help on this from the frontend side of things? I can draw up how the frontend could look like & implement it
