### ISSUE TITLE
TEAMROCKET#29: Replace getAllRecipes() with firebase endpoint

### ISSUE THREAD

**Issue by gmihir** [cse112-sp22-group3/rocketrecipes#29]
**Briefly describe the problem/feature**
Getting all recipes needs to be updated to rely on Firebase.

**Point Estimate (in Fibonacci numbers)**
3

**What area of code does this affect?**
utils.js

**What needs to be done (at a glance)?**
Modify utils.js so it gets all of the recipes from Firebase instead of from local storage.

**Additional context**
A GET request to this endpoint will return all recipes: https://rocketrecipes-6c192-default-rtdb.firebaseio.com/recipes.json

**Reviewer**
anyone

**Assignee**
anyone

**Comment by DanlandYZ** [comment]
looks like single fetch statement can retrieve all recipes
