### ISSUE TITLE
TEAMROCKET#30: Sanitize inputs 

### ISSUE THREAD

**Issue by gmihir** [cse112-sp22-group3/rocketrecipes#30]
**Briefly describe the problem/feature**
Sanitize all inputs, specifically for the create recipe and update recipe pages

**Point Estimate (in Fibonacci numbers)**
3

**What area of code does this affect?**
JS for create recipe page and update recipe page

**What needs to be done (at a glance)?**
There are a few security vulnerabilities when a user is entering input. User input should be sanitized because with our current implementation (no sanitization), arbitrary code can be run on our server.

**Additional context**
@williamcsimpson found the issue, so whoever picks up this issue/is assigned to it should talk with him on how to best fix this.

**Reviewer**
anyone

**Assignee**
anyone

**Comment by helloserina** [comment]
- Title must not contain numbers + is trimmed of whitespace
- Summary is trimmed of whitespace
- Recipe servings/amount, readyInMinutes are checked to be integers and does accept inputs that contain integers (converts to integers in this case)
- Ingredient amount must be an integer + trimmed of whitespace
- Ingredient name, units cannot contain numbers + trimmed of whitespace
- Steps are trimmed of whitespace
- The url validation already looks comprehensive so I didn't touch it
- Found a random bug preventing deleting ingredients and steps so I fixed it
