### ISSUE TITLE
TEAMROCKET#43: Image Sizing

### ISSUE THREAD

**Issue by skmartinelli** [cse112-sp22-group3/rocketrecipes#43]
**Briefly describe the problem/feature**
Image sizes can be inconsistent.

Example:
![image](https://user-images.githubusercontent.com/53798189/169200491-5fe2879e-994a-49c6-8def-30b05d1298bf.png)

**Point Estimate (in Fibonacci numbers)**
3? Hard to say. This may be beyond our scope due to the inconsistency of the database

**What area of code does this affect?**
Search page css, html, maybe js

**What needs to be done (at a glance)?**
Figure out how to standardize images to fit, stretch, or zoom such that the images are consistent. 

**Additional context**
Certain images have white or black borders as part of the image. This makes this not as simple as stretching the image because even if we stretch it the border will make it seem as though it hasn't been stretched

**Reviewer**
tbd

**Assignee**
tbd

**Comment by vchen51** [comment]
@skmartinelli yeah the problem belongs in the database bc the pictures themselves have white borders, all images should cover the space :( unfortunately we can't do anything without manually going through each picture
