### ISSUE TITLE
TEAMROCKET#50: Favorite Recipes From Search Page

### ISSUE THREAD

**Issue by skmartinelli** [cse112-sp22-group3/rocketrecipes#50]
**Briefly describe the problem/feature**
Add hearts to recipe cards so that users can add recipes from the search page

**Point Estimate (in Fibonacci numbers)**
2

**What area of code does this affect?**
Search page html js and css

**What needs to be done (at a glance)?**
- Copy and adapt the favoriteRecipe function so it can be called from the search page
- Add clickable heart icons to the recipe cards

**Additional context**
Relatively low priority ticket

**Reviewer**
TBD

**Assignee**
@skmartinelli

**Comment by DanlandYZ** [comment]
I may have an example of this in my cse110 repo
