### ISSUE TITLE
TEAMROCKET#69: Minimize Search Bar

### ISSUE THREAD

**Issue by ahthai2468** [cse112-sp22-group3/rocketrecipes#69]
**Briefly describe the problem/feature**
Something Sanat brought up during a weekly team meeting. Move/minimize the search bar so that it's not taking up such a large percentage of the screen on the home page. This is especially obvious when on a mobile device. Upon loading the home page, over half of the page does not contain recipe cards. Recipe cards are the user's main priority, but they aren't the main focus of the home page. The search bar seems to be the main focus of the home page (which is redundant if we already have a search page).

**Point Estimate (in Fibonacci numbers)**
3 likely?

**What area of code does this affect?**
index.html, custom-navbar.js, custom-searchbar.js, (maybe all html files? depends on approach)

**What needs to be done (at a glance)?**
Sanat suggested hiding the search bar and moving it up to the navbar with a search icon, which will display the search bar when clicked.  It's a bit unnecessary having a search bar on the home screen and then also a search option in the navbar, so this solution will look to remove that redundancy.

**Additional context**
Not sure, but Vanessa might have some insight since she's done some work on the navbar.

**Reviewer**
TBD

**Assignee**
TBD

**Comment by elk15** [comment]
I shrunk it a bit using the inspector tool.
![desktop](https://user-images.githubusercontent.com/84975908/170874592-eabe9d04-d9ba-49e8-ab18-5624f1d7d53d.jpg)

**Comment by elk15** [comment]
Can I attempt to work on this issue? If the search bar is moved to the navbar what do you want to do with the filters button?

**Comment by helloserina** [comment]
- custom-searchbar.js: the search bar originally present on index.html and on the searchPage.html
- custom-navbar.js: contained the original navbar, used in searchPage.html to remove search option in nav bar(redundant)
- simple-custom-navbar: contains the ability to search in the navbar, used in most html pages
- simple-custom-searchbar: the search bar for simple-custom-navbar
