### ISSUE TITLE
TEAMROCKET#75: User Personalization

### ISSUE THREAD

**Issue by gmihir** [cse112-sp22-group3/rocketrecipes#75]
**Briefly describe the problem/feature**
We have a cloud database and as a result have the opportunity to customize our application for our users. This will be accomplished with:

- [ ] a survey (launched when a user signs up) that collects their dietary restrictions (vegan, vegetarian, lactose-intolerant, gluten-free) and goal for cooking ((want something easy/cheap because college student (isEasy, cheap), cooking for my family (cheap, maybe serving size?)) and stores in firebase
- [ ] integration of preferences into application (search and recommendations weigh recipes that match their preferences

**Point Estimate (in Fibonacci numbers)**
5

**What area of code does this affect?**
New survey popup/page, logic in search/recommendations to accommodate preferences

**What needs to be done (at a glance)?**
- a survey needs to be created on user sign up
- search and recommendations should look at preferences and weigh matching things higher

**Additional context**

**Reviewer**
anyone
**Assignee**
TBD

**Comment by helloserina** [comment]
done with basic survey, branch: teamrocket-75-user-personalization
